### PR TITLE
Added Password Spraying Functionality + Timing Mechanisms

### PR DESCRIPTION
**Pull request by 0xAsh**
I really enjoy using Talon for internal assessments but was thinking it would be nice to add timing controls and password list support for low and slow password guessing. I was about to write a Bash or Python wrapper around the tool but realized it would probably be best to just implement it in the source.

## Changes:
- Added the ability to iterate through a list of passwords using the `-Passfile` argument
- Implemented timing controls for this functionality which are controlled via the `-Lockout` and `-A` flags, which correspond to the lockout period (corresponding to GPO) and number of authentication attempts to perform per lockout period, respectively.
- Reorganized the main function so if someone still just wants to use original functionality it still works

Also sorry if the code is crappy. This was my first time writing Go lol

As of now the password spraying functionality only works with the Kerberos auth method (`-K`). I tested a bunch using my personal lab and it seems like the LDAP functionality is no longer working on the main Talon release and also my updated version. (can't remember if this is intended?)

## Usage Example
Let's say we have the following list of usernames:
```
$ cat users.txt 
frodo
boromir
elrond
gandalf
legolas
gimli
aragorn
mithrandir
```

And the following list of passwords:

```
$ cat pwds.txt 
password123
pass!!!
Pa$$w0rd
Shire11boii
0n3ringggg!
lol123boromir123
```

We can perform 4 authentication attempts every 45 minutes with a 1.5 second sleep using the following:
```
./Talon -H <DC_IP> -Userfile users.txt -Passfile pwds.txt -K -D contoso.local -A 4 -Lockout 45 -sleep 1.5
```

#### In my lab it looks something like this:
image

As you can see it attempts the first four passwords from our wordlist against every user, then pauses for the lockout period. 

I'll show it with a quick lockout period so you can see that it iterates through every password (doesn't reuse passwords from the list):

image

And that's it :) hope it's useful. I'll probably be using this (extremely slowly) on engagements.

### CODE REVIEW

**Comment by hypervis0r** [comment]
Build failed, try harder next time

**Comment by Tylous** [comment]
Sorry for the delay. Let me take a look

**Comment by 0xAsh** [comment]
> Sorry for the delay. Let me take a look

Thank you!

**Comment by Tylous** [comment]
Update. What do you mean by LDAP doesn't work? I just tested and it works fine. Can you clarify before I make the change. Outside of that I just am going to update the README.

**Comment by Tylous** [comment]
@0xAsh please see my updated comment

**Comment by 0xAsh** [comment]
> Update. What do you mean by LDAP doesn't work? I just tested and it works fine. Can you clarify before I make the change. Outside of that I just am going to update the README.

Turns out that was an error in my lab since my ADCS deployment was botched. ^^ Feel free to disregard.

Thank you!

**Comment by Tylous** [comment]
Alright, stay tuned for the merge :)

**Pull request merged**
