### PR TITLE
Automate Dependencies

### PR DESCRIPTION
**Pull request by jdelta1**
Small changes to README to simplify dependency installation.

### CODE REVIEW

**Comment by perfectra1n** [comment]
Bump, this would be great to have baked in, instead of the millions of instructions.

**Comment by Tylous** [comment]
Let me look into this.

**Comment by jdelta1** [comment]
Now it can just be `go install -v github.com/optiv/Talon@latest`

**Comment by jdelta1** [comment]
See PR #8

**Pull request closed without merging**
